name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches: [ "docker-build" ]
  pull_request:
    branches: [ "docker-build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rsshub:latest

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Tag the image with 'latest' and commit SHA
    - name: Tag the Docker image
      run: |
        IMAGE_ID=rsshub:latest
        docker tag $IMAGE_ID hzhyang/rsshub:latest

    # Push the image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: |
        docker push hzhyang/rsshub:latest
