name: Docker Image CI

on:
  push:
    branches: [ "docker-build" ]
  pull_request:
    branches: [ "docker-build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rsshub:$(date +%s)

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Tag the image with 'latest' and commit SHA
    - name: Tag the Docker image
      run: |
        IMAGE_ID=rsshub:$(date +%s)
        docker tag $IMAGE_ID hzhyang/rsshub:latest
        docker tag $IMAGE_ID hzhyang/rsshub:${{ github.sha }}

    # Push the image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: |
        docker push hzhyang/rsshub:latest
        docker push hzhyang/rsshub:${{ github.sha }}
